version: '3'

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
    ipam:
    config:
      - subnet: 10.1.1.0/24

services:
  certbot:
    build:
      context: ./certbot/build
      dockerfile: Dockerfile
    container_name: certbot
    restart: unless-stopped
    env_file:
      - ./certbot/build/env
    volumes:
      - ./certbot/dist/domains.conf:/etc/letsencrypt/domains.conf
    networks:
      - backend
  php-fpm-56:
    build:
      context: ./php-fpm/build/56
      dockerfile: Dockerfile
    container_name: php-fpm-56
    ports:
      - "9000:9000"
    networks:
      backend:
        ipv4_address: 10.1.1.2
    volumes:
      - ./web/data:/web
  php-fpm-72:
    build:
      context: ./php-fpm/build/72
      dockerfile: Dockerfile
    container_name: php-fpm-72
    ports:
      - "9000:9000"
    networks:
      backend:
        ipv4_address: 10.1.1.3
    volumes:
      - ./web/data:/web
  redis:
   image: redis:4.0.11-alpine
   ports:
     - "6379:6379"
   networks:
     backend:
      ipv4_address: 10.1.1.4
  proxy:
    image: nginx:1.15.3-alpine
    container_name: proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
    depends_on:
      - certbot
    networks:
      frontend:
      backend:
        ipv4_address: 10.1.1.1
  web-blog-rayriffy-com:
    build:
      context: ./web/build
      dockerfile: Dockerfile
    container_name: web-blog-rayriffy-com
    restart: unless-stopped
    environment:
      - SERVER_NAME=blog.rayriffy.com
      - PHP_BACKEND=php-fpm-72
      - ROOT=/web/blog.rayriffy.com
    ports:
      - "8001:80"
    depends_on:
      - php-fpm-72
      - proxy
      - redis
    links:
      - php-fpm-72
    volumes:
      - ./web/data/blog.rayriffy.com:/web/blog.rayriffy.com
    networks:
      backend:
        ipv4_address: 10.1.2.1