version: '3'

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
    ipam:
    config:
      - subnet: 10.1.1.0/24

services:
  certbot:
    image: adferrand/letsencrypt-dns
    container_name: certbot
    restart: unless-stopped
    env_file:
      - ./certbot/build/env
    volumes:
      - ./certbot/dist/domains.conf:/etc/letsencrypt/domains.conf
    networks:
      - backend
  php-fpm-56:
    build:
      context: ./php-fpm/build/56
      dockerfile: Dockerfile
    container_name: php-fpm-56
    ports:
      - "9001:9000"
    networks:
      backend:
        ipv4_address: 10.1.1.2
  php-fpm-72:
    build:
      context: ./php-fpm/build/72
      dockerfile: Dockerfile
    container_name: php-fpm-72
    ports:
      - "9000:9000"
    networks:
      backend:
        ipv4_address: 10.1.1.3
  redis:
   image: redis:4.0.11-alpine
   ports:
     - "6379:6379"
   networks:
     backend:
      ipv4_address: 10.1.1.4
  proxy:
    image: nginx:1.15.3-alpine
    container_name: proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf:/etc/nginx
    depends_on:
      - certbot
      - php-fpm-56
      - php-fpm-72
    links:
      - certbot
    networks:
      - frontend
      backend:
        ipv4_address: 10.1.1.1
  # app:
  #   build:
  #     context: ./app/build
  #     dockerfile: Dockerfile
  #   container_name: app1
  #   ports:
  #     - "49152:49152"
  #   volumes:
  #     - ./app/dist/blog.rayriffy.com/web:/usr/share/nginx/html
  #     - ./app/dist/blog.rayriffy.com/conf/
  #   depends_on:
  #     - proxy
  #   network:
  #     backend:
  #       ipv4_address: 10.1.1.5