version: '3'

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge

volumes:
  ssl-cert: 

services:
  certbot:
    image: adferrand/letsencrypt-dns:2.5.3
    container_name: certbot
    restart: unless-stopped
    env_file:
      - ./certbot/build/env
    volumes:
      - ./certbot/dist/domains.conf:/etc/letsencrypt/domains.conf
      - ssl-cert:/etc/letsencrypt/live
    networks:
      - backend
  php-fpm-54:
    build:
      context: ./php-fpm/build/54
      dockerfile: Dockerfile
    container_name: php-fpm-54
    networks:
      - backend
    volumes:
      - ./web/data:/web
  php-fpm-56:
    build:
      context: ./php-fpm/build/56
      dockerfile: Dockerfile
    container_name: php-fpm-56
    networks:
      - backend
    volumes:
      - ./web/data:/web
  php-fpm-72:
    build:
      context: ./php-fpm/build/72
      dockerfile: Dockerfile
    container_name: php-fpm-72
    networks:
      - backend
    volumes:
      - ./web/data:/web
  redis:
    image: redis:4.0.11-alpine
    networks:
      - backend
  proxy:
    image: nginx:1.15.3-alpine
    container_name: proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
      - ssl-cert:/etc/letsencrypt/live
    depends_on:
      - certbot
    networks:
      - frontend
      - backend
  web-blog-rayriffy-com:
    build:
      context: ./web/build
      dockerfile: Dockerfile
    container_name: web-blog-rayriffy-com
    restart: unless-stopped
    environment:
      - SERVER_NAME=blog.rayriffy.com
      - PHP_BACKEND=php-fpm-72
      - ROOT=/web/blog.rayriffy.com
    depends_on:
      - php-fpm-72
    links:
      - php-fpm-72
    volumes:
      - ./web/data/blog.rayriffy.com:/web/blog.rayriffy.com
    networks:
      - backend